### ISSUE TITLE
Exclude new.min.css and lite.css from source

### ISSUE THREAD

**Issue by cbhp** [xz/new.css#15]
`new.min.css` and `lite.css` are auto-generated based on `new.css` so they should not be part of the source but provided as artifacts via releases.

**Comment by 3x** [comment]
Good point. In your opinion, would be the best way to accomplish this? Instead of using `https://newcss.net/new.min.css`, should a version-based URL be used, such as `https://newcss.net/dist/1.0.0/new.min.css`?

**Comment by cbhp** [comment]
My initial thoughts were about the code repo, not about delivery. 
Files which can be built from the source should not be maintained within in the source.
As we can already see there have been merge conflicts caused by the minimized css.

But also for delivery, it's typical to provide version-specific urls. Examples:
- https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css
- https://code.jquery.com/jquery-3.5.1.min.js

**Comment by 3x** [comment]
:+1: Was fixed in 1.1.0 (https://github.com/xz/new.css/commit/788be93b4a66c50f11f05f73d1db094159058046).

jsDelivr automatically auto-minifies the new.css file, so just pushing an update to npm makes it available. 

`lite.css` is now redundant as fonts are no longer imported by default. The old CDN URLs on the `newcss.net` domain will stay the same, this change is only applicable for versions 1.1.0+.
